DROP TABLE IF EXISTS race;
CREATE TABLE race
(
    race_id               BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name                  VARCHAR(255),
    description           VARCHAR(255),
    place                 VARCHAR(255),
    day                   TIMESTAMP,
    description_url       VARCHAR(255),
    host                  VARCHAR(255),
    phone_number          VARCHAR(255),
    start_of_registration TIMESTAMP,
    end_of_registration   TIMESTAMP,
    entry_fee             INTEGER,
    created_by            VARCHAR(255) NOT NULL,
    created_at            TIMESTAMP    NOT NULL,
    modified_by           VARCHAR(255) NOT NULL,
    modified_at           TIMESTAMP    NOT NULL
);

DROP TABLE IF EXISTS race_aud;
CREATE TABLE race_aud
(
    rev                   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    rev_type               SMALLINT     NOT NULL,
    race_id               BIGINT,
    name                  VARCHAR(255),
    description           VARCHAR(255),
    place                 VARCHAR(255),
    day                   TIMESTAMP,
    description_url       VARCHAR(255),
    host                  VARCHAR(255),
    phone_number          VARCHAR(255),
    start_of_registration TIMESTAMP,
    end_of_registration   TIMESTAMP,
    entry_fee             INTEGER,
    created_by            VARCHAR(255) NOT NULL,
    created_at            TIMESTAMP    NOT NULL,
    modified_by           VARCHAR(255) NOT NULL,
    modified_at           TIMESTAMP    NOT NULL
);